# Generated by Django 4.0.10 on 2023-10-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        ("blueprints", "0005_alter_blueprint_location_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blueprint",
            name="eve_type",
            field=models.ForeignKey(
                help_text="Blueprint type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="location",
            field=models.ForeignKey(
                help_text="Blueprint location",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blueprints",
                to="blueprints.location",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="owner",
            field=models.ForeignKey(
                help_text="Corporation that owns the blueprint",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blueprints",
                to="blueprints.owner",
            ),
        ),
    ]
